export default [
  {
    id: 1,
    address: "山西省太原市小店区 山西白求恩医院(山西医学科学院)",
    addressDetail: "山西省太原市小店区 山西白求恩医院(山西医学科学院)",
    areaCode: "140105",
    city: "太原市",
    country: "",
    county: "小店区",
    isDefault: true,
    name: "樊先生",
    postalCode: "030000",
    province: "山西省",
    tel: "13010102020",
  },
  {
    id: 2,
    address: "上海市闵行区 虹桥火车站",
    addressDetail: "上海市闵行区 虹桥火车站",
    areaCode: "310112",
    city: "上海市",
    country: "",
    county: "闵行区",
    isDefault: false,
    name: "樊先生",
    postalCode: "201100",
    province: "上海市",
    tel: "13010102020",
  },
]
